import { db } from '@/db';
import { movies } from '@/db/schema';

async function main() {
    const sampleMovies = [
        {
            title: 'The Shawshank Redemption',
            genre: 'Drama',
            releaseYear: 1994,
            director: 'Frank Darabont',
            rating: 5.0,
            posterImageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400&h=600&fit=crop',
            description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
            duration: '2 Hour 22 Min',
            downloadLink: 'https://example.com/download/movie-1',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'Onward',
            genre: 'Animation/Adventure',
            releaseYear: 2020,
            director: 'Dan Scanlon',
            rating: 4.0,
            posterImageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400&h=600&fit=crop',
            description: 'Two elven brothers embark on a quest to bring their father back for one day.',
            duration: '1 Hour 42 Min',
            downloadLink: 'https://example.com/download/movie-2',
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            title: 'Descendants 3',
            genre: 'Musical/Fantasy',
            releaseYear: 2019,
            director: 'Kenny Ortega',
            rating: 3.0,
            posterImageUrl: 'https://images.unsplash.com/photo-1594908900066-3f47337549d8?w=400&h=600&fit=crop',
            description: 'The teenagers of Disney\'s most infamous villains return to the Isle of the Lost to recruit a new batch of villainous offspring.',
            duration: '1 Hour 46 Min',
            downloadLink: 'https://example.com/download/movie-3',
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            title: 'A Christmas Carol',
            genre: 'Drama/Fantasy',
            releaseYear: 2009,
            director: 'Robert Zemeckis',
            rating: 4.0,
            posterImageUrl: 'https://images.unsplash.com/photo-1512149177596-f817c7ef5d4c?w=400&h=600&fit=crop',
            description: 'An animated retelling of Charles Dickens\' classic novel about a Victorian-era miser taken on a journey of self-redemption.',
            duration: '1 Hour 36 Min',
            downloadLink: 'https://example.com/download/movie-4',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            title: 'Aladdin',
            genre: 'Adventure/Fantasy',
            releaseYear: 2019,
            director: 'Guy Ritchie',
            rating: 4.0,
            posterImageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400&h=600&fit=crop',
            description: 'A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.',
            duration: '2 Hour 8 Min',
            downloadLink: 'https://example.com/download/movie-5',
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            title: 'The Princess and the Frog',
            genre: 'Animation',
            releaseYear: 2009,
            director: 'Ron Clements',
            rating: 4.0,
            posterImageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop',
            description: 'A waitress, desperate to fulfill her dreams as a restaurant owner, is set on a journey to turn a frog prince back into a human being.',
            duration: '1 Hour 37 Min',
            downloadLink: 'https://example.com/download/movie-6',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            title: 'Inception',
            genre: 'Sci-Fi/Thriller',
            releaseYear: 2010,
            director: 'Christopher Nolan',
            rating: 5.0,
            posterImageUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=400&h=600&fit=crop',
            description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
            duration: '2 Hour 28 Min',
            downloadLink: 'https://example.com/download/movie-7',
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            title: 'The Dark Knight',
            genre: 'Action/Crime',
            releaseYear: 2008,
            director: 'Christopher Nolan',
            rating: 5.0,
            posterImageUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400&h=600&fit=crop',
            description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
            duration: '2 Hour 32 Min',
            downloadLink: 'https://example.com/download/movie-8',
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            title: 'Interstellar',
            genre: 'Sci-Fi/Adventure',
            releaseYear: 2014,
            director: 'Christopher Nolan',
            rating: 4.5,
            posterImageUrl: 'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=400&h=600&fit=crop',
            description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
            duration: '2 Hour 49 Min',
            downloadLink: 'https://example.com/download/movie-9',
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            title: 'The Grand Budapest Hotel',
            genre: 'Comedy/Drama',
            releaseYear: 2014,
            director: 'Wes Anderson',
            rating: 4.5,
            posterImageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400&h=600&fit=crop',
            description: 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.',
            duration: '1 Hour 39 Min',
            downloadLink: 'https://example.com/download/movie-10',
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            title: 'Mad Max: Fury Road',
            genre: 'Action/Sci-Fi',
            releaseYear: 2015,
            director: 'George Miller',
            rating: 4.5,
            posterImageUrl: 'https://images.unsplash.com/photo-1533613220915-609f661a6fe1?w=400&h=600&fit=crop',
            description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
            duration: '2 Hour 0 Min',
            downloadLink: 'https://example.com/download/movie-11',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            title: 'Parasite',
            genre: 'Thriller/Drama',
            releaseYear: 2019,
            director: 'Bong Joon-ho',
            rating: 4.5,
            posterImageUrl: 'https://images.unsplash.com/photo-1574267432644-f3db13f51e82?w=400&h=600&fit=crop',
            description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
            duration: '2 Hour 12 Min',
            downloadLink: 'https://example.com/download/movie-12',
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            title: 'Spider-Man: Into the Spider-Verse',
            genre: 'Animation/Action',
            releaseYear: 2018,
            director: 'Bob Persichetti',
            rating: 4.5,
            posterImageUrl: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?w=400&h=600&fit=crop',
            description: 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.',
            duration: '1 Hour 57 Min',
            downloadLink: 'https://example.com/download/movie-13',
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            title: 'Get Out',
            genre: 'Horror/Thriller',
            releaseYear: 2017,
            director: 'Jordan Peele',
            rating: 4.0,
            posterImageUrl: 'https://images.unsplash.com/photo-1603385602394-f0c0d0c6edb2?w=400&h=600&fit=crop',
            description: 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',
            duration: '1 Hour 44 Min',
            downloadLink: 'https://example.com/download/movie-14',
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            title: 'Arrival',
            genre: 'Sci-Fi/Drama',
            releaseYear: 2016,
            director: 'Denis Villeneuve',
            rating: 4.0,
            posterImageUrl: 'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=400&h=600&fit=crop',
            description: 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.',
            duration: '1 Hour 56 Min',
            downloadLink: 'https://example.com/download/movie-15',
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
    ];

    await db.insert(movies).values(sampleMovies);
    
    console.log('✅ Movies seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});